"""Write MORNING_STATUS.md summarising overnight progress.

Reads:
  - training/eval/*.json     - all eval scorecards
  - training/checkpoints/*/  - all trained adapters with manifests
  - training/overnight_logs/ - orchestrator logs and step markers
  - training/data/stats.json - dataset stats

Writes:
  - MORNING_STATUS.md  in repo root
"""

from __future__ import annotations

import datetime as dt
import json
import os
import subprocess
from pathlib import Path


REPO = Path("/Users/amitmishra/worksppace-central/demo-bimplus/bim-coordinator")


def _load_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return None


def _gemma_status() -> str:
    """Show what Gemma variants are downloaded."""
    base = Path.home() / ".cache/huggingface/hub"

    parts = []
    # E2B bf16 (3 shards expected)
    e2b_bf16_count = len(list(base.glob("models--mlx-community--gemma-4-e2b-it-bf16/snapshots/*/model-*.safetensors")))
    parts.append(f"E2B bf16: {e2b_bf16_count}/3" + (" ✅" if e2b_bf16_count >= 3 else ""))
    # E4B bf16 (4 shards expected)
    e4b_bf16_count = len(list(base.glob("models--mlx-community--gemma-4-e4b-it-bf16/snapshots/*/model-*.safetensors")))
    parts.append(f"E4B bf16: {e4b_bf16_count}/4" + (" ✅" if e4b_bf16_count >= 4 else ""))
    # E2B 4-bit (single file)
    e2b_4bit = bool(list(base.glob("models--mlx-community--gemma-4-e2b-it-4bit/snapshots/*/model.safetensors")))
    parts.append(f"E2B 4-bit: {'✅ ready' if e2b_4bit else '⏳ downloading'}")
    # E4B 4-bit (single file)
    e4b_4bit = bool(list(base.glob("models--mlx-community--gemma-4-e4b-it-4bit/snapshots/*/model.safetensors")))
    parts.append(f"E4B 4-bit: {'✅ ready' if e4b_4bit else '⏳ downloading'}")
    return " · ".join(parts)


def _scorecard_table(evals: list[tuple[str, dict]]) -> str:
    """Render a comparison table of evaluation scorecards."""
    if not evals:
        return "_(no completed evals yet)_"

    metrics = [
        ("top1_acc", "Top-1", True),
        ("top4_acc", "Top-4", True),
        ("format_valid", "Format", True),
        ("faithful", "Faithful", True),
        ("latency_p50_s", "p50 (s)", False),
        ("latency_p95_s", "p95 (s)", False),
    ]

    header = "| Model | " + " | ".join(m[1] for m in metrics) + " |"
    sep = "|---|" + "---|" * len(metrics)
    rows = [header, sep]

    for label, sc in evals:
        cells = [f"**{label}**"]
        for key, _, is_pct in metrics:
            v = sc.get(key)
            if v is None:
                cells.append("-")
            elif is_pct:
                cells.append(f"{v:.1%}")
            else:
                cells.append(f"{v:.2f}")
        rows.append("| " + " | ".join(cells) + " |")

    return "\n".join(rows)


def _running_processes() -> str:
    """Return a list of running mlx_lm/hf-download/caffeinate processes."""
    try:
        out = subprocess.check_output(
            ["ps", "-axo", "pid,command"],
            text=True, stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return "_(unable to read process list)_"
    keep = []
    for line in out.splitlines():
        s = line.strip()
        if any(needle in s for needle in ("mlx_lm lora", "hf download", "caffeinate")):
            # Skip the grep/ps invocation itself
            if "grep " in s or "ps -axo" in s:
                continue
            keep.append(s[:140])
    if not keep:
        return "_(no training/download processes running)_"
    return "\n".join(f"- `{l}`" for l in keep[:8])


def _step_markers() -> dict[str, bool]:
    log_dir = REPO / "training" / "overnight_logs"
    if not log_dir.exists():
        return {}
    out = {}
    for marker in log_dir.glob(".*.done"):
        out[marker.stem.lstrip(".")] = True
    return out


def main() -> None:
    now = dt.datetime.now()
    eval_dir = REPO / "training" / "eval"

    # Load all eval scorecards
    evals: list[tuple[str, dict]] = []
    for f in sorted(eval_dir.glob("*.json")):
        data = _load_json(f)
        if data and "scorecard" in data:
            evals.append((f.stem, data["scorecard"]))

    # Load dataset stats
    stats = _load_json(REPO / "training" / "data" / "stats.json")

    # Find checkpoints
    ckpt_dir = REPO / "training" / "checkpoints"
    ckpts = sorted([p for p in ckpt_dir.glob("*-real-*") if p.is_dir()])
    smoke_ckpts = sorted([p for p in ckpt_dir.glob("smoke-*") if p.is_dir()])

    # Find best top-4 score among non-baseline evals
    best = None
    for label, sc in evals:
        if "baseline" in label:
            continue
        score = sc.get("top4_acc", 0)
        if best is None or score > best[1]:
            best = (label, score)

    markers = _step_markers()
    completed_steps = sorted(markers.keys())

    lines = [
        f"# Morning Status — {now:%Y-%m-%d %H:%M}",
        "",
        "Auto-generated by overnight orchestrator. Latest update at the time shown above.",
        "",
        "## TL;DR",
        "",
    ]

    if best:
        lines.append(f"- 🏆 **Best fine-tuned model so far:** `{best[0]}` — top-4 accuracy {best[1]:.1%}")
    else:
        lines.append("- ⏳ No fine-tuned model evaluated yet")

    lines.extend([
        f"- 📊 **Evaluations run:** {len(evals)}",
        f"- 💾 **Checkpoints saved:** {len(ckpts)} (real) + {len(smoke_ckpts)} (smoke)",
        f"- ✅ **Steps completed:** {len(completed_steps)}",
        f"- 📥 **Gemma 4 download:** {_gemma_status()}",
        "",
        "## Scorecard comparison",
        "",
        _scorecard_table(evals),
        "",
        "## Completed steps",
        "",
    ])

    for step in completed_steps:
        lines.append(f"- ✅ `{step}`")
    if not completed_steps:
        lines.append("_(none yet)_")

    lines.extend([
        "",
        "## Currently running",
        "",
        _running_processes(),
        "",
        "## Dataset",
        "",
    ])

    if stats:
        lines.append(f"- Total examples: **{stats['total_examples']}** (train {stats['train']} / val {stats['valid']} / test {stats['test']})")
        lines.append(f"- Templates used: {stats['n_templates']} × {stats['n_per_template']} briefs each")
        lines.append("- Top personas: " + ", ".join(f"{k} ({v})" for k, v in list(stats['personas'].items())[:5]))
    else:
        lines.append("_(stats.json not found)_")

    lines.extend([
        "",
        "## Checkpoints",
        "",
    ])
    for ckpt in ckpts:
        manifest = _load_json(ckpt / "manifest.json")
        if manifest:
            lines.append(f"- `{ckpt.name}` — {manifest.get('iters')} iters, {manifest.get('duration_s', 0)//60} min")
        else:
            adapter = ckpt / "adapters.safetensors"
            if adapter.exists():
                size_mb = adapter.stat().st_size / 1024 / 1024
                lines.append(f"- `{ckpt.name}` — adapter {size_mb:.1f} MB (training in progress or interrupted)")
    if not ckpts:
        lines.append("_(no real checkpoints yet)_")

    lines.extend([
        "",
        "## Next steps when you wake up",
        "",
    ])

    if best:
        lines.extend([
            "1. Review scorecard above — winner is the best top-4 model",
            f"2. Quantize winner to GGUF: `python training/scripts/merge_and_export.py --adapter training/checkpoints/<winner>`",
            "3. Deploy to GCP Cloud Run: `bash training/deploy/cloud_run/deploy.sh` (set PROJECT_ID, GGUF_PATH first)",
            "4. Wire endpoint into demo frontend",
        ])
    else:
        lines.extend([
            "1. Check `training/overnight_logs/orchestrator.log` for what happened",
            "2. If training crashed, look at the per-step logs (`train_LLAMA32.log` etc.)",
            "3. Re-run orchestrator (idempotent — skips completed steps)",
        ])

    lines.extend([
        "",
        "## Logs",
        "",
        f"- `training/overnight_logs/orchestrator.log` — top-level decisions",
        f"- `training/overnight_logs/train_*.log` — per-model training logs",
        f"- `training/overnight_logs/eval_*.log` — per-eval logs",
        f"- `training/eval/*.json` — full per-example results",
        "",
    ])

    out_path = REPO / "MORNING_STATUS.md"
    out_path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
